[WIP] Add project cards and team bullets to theme
18F/federalist-modern-team-template pull request #19
Opened 2017-05-17 22:50 UTC by hbillings

Closes #915.

Notable changes:
- Projects now use collections instead of the `projects.yml` and `projects` folder. This combines the data for projects into a single point (the project markdown file).

To do:
- [ ] Add project style from OES
- [ ] Add team collection
- [ ] Add team style from OES

2017-05-22 17:03 UTC, hbillings commented on README.md
> +
I'm curious for feedback on this approach. I could have just named the files `uswds.css`/`uswds.min.js`, and then the only thing necessary for updating would be overwriting those files with new ones. That approach has the downside of clobbering old files, though, which makes it potentially difficult to revert to old files if the new ones do unexpected things. It also makes it difficult to tell which version of the standards the template is running.

2017-05-22 17:05 UTC, wslack commented on README.md
> +
I think the README needs an example entry in _config.yml but this is otherwise good to use. Also, is there a specific link to download the code?

2017-05-22 17:12 UTC, hbillings commented on README.md
> +
Good call -- I added that example and a more specific link to the downloads!

2017-05-22 17:54 UTC, wslack commented on README.md
> +
cool; happy to review when out of [WIP]!

2017-05-23 01:11 UTC, hbillings commented
Updated the footer pretty radically to use the WDS medium footer. It looks like this now, and there are more options for it in the config:
<img width="1150" alt="screen shot 2017-05-22 at 7 09 29 pm" src="https://cloud.githubusercontent.com/assets/509309/26334445/666feb26-3f22-11e7-9f2b-13de1605ed45.png">

2017-05-23 04:13 UTC, wslack commented
https://federalist.fr.cloud.gov/preview/18f/federalist-modern-team-template/add-project-and-team-cards/ looking really good so far!

2017-05-24 00:44 UTC, hbillings commented
Okay, I think that except for the rejiggering I want to do with how WDS is included, this is basically done. @jseppi @jmhooper @wslack, please comb this over as much as you like and raise any issues you'd like me to fix here.

2017-05-24 14:59 UTC, wslack requested changes
- USA flag in header doesn't load
- What we do section in homepage has text spacing that is too wide
- "return to top" occupies a lot of horizontal real estate; should it be moved?

2017-05-24 22:37 UTC, hbillings commented
@wslack Thanks for catching the images! They should be fixed now.

Do you mean the space between lines is too big? I bumped up the text on the home page to use the settings for the `usa-font-lead` p tags. I can take it back to the same text size as is used on the rest of the site.

We could probably drop the return to top link if we want. (Or we could hide it so it's there for screen readers only.)

2017-05-24 23:13 UTC, hbillings commented
Of note: I changed the way WDS is included (and changed the README to reflect the easier, less-error-prone system).

2017-05-25 14:25 UTC, wslack commented
> Do you mean the space between lines is too big?

There's probably just too much text there, it looks like a wall. Agreed we can drop the "return to top" link.

2017-05-25 14:25 UTC, wslack requested changes
Page title is cutoff when viewed in mobile

2017-05-25 18:02 UTC, wslack approved these changes

2017-05-25 18:02 UTC, wslack commented
ready to merge when you are!

2017-05-26 16:40 UTC, merged